### ISSUE TITLE
Is there any plan to support python 3.9 or 3.10?

### ISSUE THREAD

**Issue by moefear85** [asb-capfan/TkZinc#2]
the python setup script doesn't work with python 3.9. I would have been willing to translate the syntax, but it seems most of the code is c++. I wouldn't know where to begin porting

**Comment by asb-capfan** [comment]
I assume you mean the Python library here: https://github.com/asb-capfan/TkZinc/tree/main/Python
Maybe you can give it a try. The result sould be a python library that works. 

In case we encounter C/C++ parts, I cannot help either, unfortunately.

**Comment by moefear85** [comment]
yes but you need to provide perl rquirements

**Comment by moefear85** [comment]
I managed to translate the Python bindings to python3. It works, and I'm seeing the following image:

![image](https://user-images.githubusercontent.com/39313692/175832065-7f59c515-0e29-4d1f-ba59-969f8de991ce.png)

however, the lines and curves are drawn very ugly, because there is no anti-aliasing. Is there a way to enable/force the use of anti-aliasing at the open-gl level?
